In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [12]:
x=np.array([9,90,5,6,7,2,10,11,19,99])
x=x.reshape(-1,1)
y=np.array([1,2,5,4,3,2,6,7,8,9])
x

array([[ 9],
       [90],
       [ 5],
       [ 6],
       [ 7],
       [ 2],
       [10],
       [11],
       [19],
       [99]])

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=1)

In [14]:
alg1=LinearRegression()

In [15]:
alg1.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [16]:
alg1.coef_

array([-0.01527339])

In [17]:
alg1.intercept_ 

4.171338333991315

In [20]:
y_predict=alg1.predict(x_train)

In [19]:
alg1.score(x_train,y_train)

0.03151409724963805

In [21]:
y_predict

array([4.0644246 , 4.03387781, 4.07969799, 2.79673312, 4.00333103,
       3.8811439 , 4.14079155])